### ISSUE TITLE
可以设置状态栏的Drawable颜色？

### ISSUE THREAD

**Issue by 0barman** [niorgai/StatusBarCompat#23]

**Comment by niorgai** [comment]
改变状态栏的颜色和drawable颜色有什么区别？
Sent from Mail Master
在2017年05月13日 11:57，52932 写道： 

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/niorgai/StatusBarCompat","title":"niorgai/StatusBarCompat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/niorgai/StatusBarCompat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"可以设置状态栏的Drawable颜色？ (#23)"}],"action":{"name":"View Issue","url":"https://github.com/niorgai/StatusBarCompat/issues/23"}}}
