### ISSUE TITLE
使用translucentStatusBar时，如果有标题，如何设置标题不和状态栏重叠？

### ISSUE THREAD

**Issue by WooYu** [niorgai/StatusBarCompat#25]
是为标题设置一个顶部的padding吗

**Comment by niorgai** [comment]
是可以这么做，记得切换的时候移除 padding 就好了。
可是我觉得你这种情况不该用这个方法。。
Sent from Mail Master
在2017年07月22日 17:24，Rain 写道： 是为标题设置一个顶部的padding吗

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/niorgai/StatusBarCompat","title":"niorgai/StatusBarCompat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/niorgai/StatusBarCompat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"使用translucentStatusBar时，如果有标题，如何设置标题不和状态栏重叠？ (#25)"}],"action":{"name":"View Issue","url":"https://github.com/niorgai/StatusBarCompat/issues/25"}}}

**Comment by WooYu** [comment]
那该用什么？还是本来就处理了这种情况。

**Comment by niorgai** [comment]
我在文档中写的是我提供了两种兼容模式。
着色模式是把 ContentView 填充在状态栏下面，然后状态栏单独着色。
全屏模式是把 ContentView 填充整个屏幕，包括状态栏。
我认为你该用 setStatusBarColor 方法。
Sent from Mail Master
在2017年07月23日 14:18，Rain 写道： 那该用什么？还是本来就处理了这种情况。

Sent from my iPhone

> On 23 Jul 2017, at 1:21 PM, JQ <notifications@github.com> wrote:
> 
> 
> 是可以这么做，记得切换的时候移除 padding 就好了。
> 可是我觉得你这种情况不该用这个方法。。
> Sent from Mail Master
> 在2017年07月22日 17:24，Rain 写道： 是为标题设置一个顶部的padding吗
> 
> —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/niorgai/StatusBarCompat","title":"niorgai/StatusBarCompat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/niorgai/StatusBarCompat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"使用translucentStatusBar时，如果有标题，如何设置标题不和状态栏重叠？ (#25)"}],"action":{"name":"View Issue","url":"https://github.com/niorgai/StatusBarCompat/issues/25"}}}
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/niorgai/StatusBarCompat","title":"niorgai/StatusBarCompat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/niorgai/StatusBarCompat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@WooYu in #25: 那该用什么？还是本来就处理了这种情况。\n\nSent from my iPhone\n\n\u003e On 23 Jul 2017, at 1:21 PM, JQ \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e \n\u003e 是可以这么做，记得切换的时候移除 padding 就好了。\n\u003e 可是我觉得你这种情况不该用这个方法。。\n\u003e Sent from Mail Master\n\u003e 在2017年07月22日 17:24，Rain 写道： 是为标题设置一个顶部的padding吗\n\u003e \n\u003e —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e \n\u003e {\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/niorgai/StatusBarCompat\",\"title\":\"niorgai/StatusBarCompat\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/niorgai/StatusBarCompat\"}},\"updates\":{\"snippets\":[{\"icon\":\"DESCRIPTION\",\"message\":\"使用translucentStatusBar时，如果有标题，如何设置标题不和状态栏重叠？ (#25)\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/niorgai/StatusBarCompat/issues/25\"}}}\n\u003e —\n\u003e You are receiving this because you authored the thread.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Issue","url":"https://github.com/niorgai/StatusBarCompat/issues/25#issuecomment-317232109"}}}

**Comment by niorgai** [comment]
@WooYu 解决了吗

**Comment by WooYu** [comment]
解决了谢谢
